language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnupg2
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
  - gunzip GeoIP.dat.gz
  - gunzip GeoIPv6.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - gunzip GeoLiteCityv6.dat.gz
  - sudo mkdir -p /usr/share/GeoIP
  - sudo mv G*.dat /usr/share/GeoIP/
  - sudo rm -rf ~/.gnupg
  - sudo gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys $GPG_KEY
  - sudo gpg -a --export $GPG_KEY | sudo apt-key add -
  - sudo chmod 600 ~/.gnupg/gpg.conf
  - sudo chmod 700 ~/.gnupg
  - sudo gpg --list-key
  - sudo echo "deafult-key $GPG_KEY" >> ~/.gnupg/gpg.conf
  - sudo cat ~/.gnupg/gpg.conf

install:
  - mvn install

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\$OSSRH_USER</username><password>\$OSSRH_PASS</password></server></servers><profiles><profile><id>gpg</id><properties><gpg.passphrase>$GPG_PASS</gpg.passphrase><gpg.keyname>$GPG_KEY</gpg.keyname></properties></profile></profiles></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml

notifications:
  email:
    recipients:
      - christiangda@gmail.com
    on_success: change
    on_failure: always