language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_install:
  - sudo apt-get update -qq
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
  - gunzip GeoIP.dat.gz
  - gunzip GeoIPv6.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - gunzip GeoLiteCityv6.dat.gz
  - sudo mkdir -p /usr/share/GeoIP
  - sudo mv G*.dat /usr/share/GeoIP/

install: mvn clean test

notifications:
  email:
    recipients:
      - christiangda@gmail.com
    on_success: change
    on_failure: always
