language: java
sudo: false

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_install:
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - wget -nv http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
  - gunzip GeoIP.dat.gz
  - gunzip GeoIPv6.dat.gz
  - gunzip GeoLiteCity.dat.gz
  - gunzip GeoLiteCityv6.dat.gz
  - mkdir -p /usr/share/GeoIP
  - mv G*.dat /usr/share/GeoIP/
  - rm -rf ~/.gnupg
  - gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 9F4A8457
  - gpg2 -a --export 9F4A8457 | sudo apt-key add -

install:
  - mvn install

after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml

notifications:
  email:
    recipients:
      - christiangda@gmail.com
    on_success: change
    on_failure: always